# Generated by Django 2.1.4 on 2019-01-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruktor',
            fields=[
                ('wspinacz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebApp.Wspinacz')),
                ('stopien_instruktorski', models.CharField(max_length=255)),
            ],
            bases=('WebApp.wspinacz',),
        ),
    ]
