# Generated by Django 2.1.4 on 2019-01-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20190118_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posiadasprzet',
            old_name='ilosc',
            new_name='ilosc_sprzetu',
        ),
        migrations.RemoveField(
            model_name='posiadasprzet',
            name='sprzet',
        ),
        migrations.AddField(
            model_name='posiadasprzet',
            name='nazwa_sprzetu',
            field=models.CharField(choices=[('lina_poj', 'Lina pojedyncza'), ('lina pol', 'Lina połówkowa'), ('lina bliz', 'Lina bliźniacza'), ('hms', 'Karabinek HMS'), ('ekspres', 'Ekspres'), ('ekspres gor', 'Eskpres górski'), ('zestaw kosci', 'Zestaw kości'), ('zestaw kosci mech', 'Zestaw kości mechanicznych'), ('sr lodowa', 'Śruba lodowa')], default='sprzet', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sprzet',
        ),
    ]
