# Generated by Django 2.1.4 on 2019-01-18 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20190118_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiadomosc', models.CharField(max_length=255)),
                ('nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nadawca', to='WebApp.Wspinacz')),
                ('odbiorca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odbiorca', to='WebApp.Wspinacz')),
            ],
        ),
    ]
