# Generated by Django 2.1.4 on 2019-01-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_wiadomosc_data_wyslania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wspinacz',
            name='ubezpieczenie',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
